# .travis.yml
services:
  - mysql
language: python
python:
  - "3.6"
env:
  - "DBUSER=root TEST=1"
before_install:
  - "sudo locale-gen cs_CZ"
install:
  - "pip install -r requirements.txt"
script:
  - "./manage.py test"
