# .travis.yml

services:
  - "mysql"

language:
  - "python"

python:
  - "3.6"

env:
  - "DBUSER=root TEST=1"

addons:
  apt:
    packages:
    - "ruby"

before_install:
  - "sudo locale-gen cs_CZ"
  - "sudo gem install compass"

install:
  - "pip install -r requirements.txt"
  - "./dosass"
  - "./manage.py collectstatic --noinput --ignore='*.scss' --ignore='*.map'" 

script:
  - "./manage.py test --failfast"
