# .travis.yml

language: "python"

sudo:  "required"

python:
  - "3.5"
  - "3.6"
  - "nightly"

services:
  - "mysql"

addons:
  apt:
    packages:
    - "ruby-dev"
    - "libtidy"

env:
  global:
    - "DBUSER=root"
  matrix:
    - "DJANGO_VERSION=requirements"
    - "DJANGO_VERSION=nightly"

before_install:
  - "sudo apt-get update"
  - "sudo apt-get upgrade libtidy"
  - "sudo locale-gen cs_CZ"
  - "gem install compass"
  - |
    if [ "$DJANGO_VERSION" == nightly ]; then
        pip install git+https://github.com/django/django.git
        pip install -r <(cat requirements.txt | grep -v -e '^Django==')
    else
        pip install -r requirements.txt
    fi

install:
  - "./dosass"
  - "./manage.py collectstatic --noinput --ignore='*.scss' --ignore='*.map'" 

script:
  - "./manage.py test --failfast && ./manage.py test --reverse --failfast"
