# .travis.yml

language: "python"

sudo: "false"

env:
  global:
    - "TEST=1"
    - "DBUSER=root"

matrix:
  include:
    - python: "3.5"
      env: "DJANGO_VERSION=stable CHECK_HTML=1"
    - python: "3.6"
      env: "DJANGO_VERSION=stable CHECK_HTML=1 DEPLOY=1"
    - python: "3.6"
      env: "DJANGO_VERSION=nightly"

before_install:
  - "openssl aes-256-cbc -K $encrypted_447d660d3eed_key -iv $encrypted_447d660d3eed_iv -in .travis_id_rsa.enc -out .travis_id_rsa -d"
  - "mkdir -p ~/.ssh"
  - "cp .travis_id_rsa ~/.ssh/id_rsa"
  - "chmod 600 ~/.ssh/id_rsa"
  - "pushd ~/builds"
  - "mkdir -p lib"
  - "export LD_LIBRARY_PATH=$(pwd)/lib"
  - "git clone --depth=1 https://github.com/htacg/tidy-html5.git htacg/tidy-html5"
  - "pushd htacg/tidy-html5/build/cmake"
  - "cmake ../.. -DCMAKE_BUILD_TYPE=Release"
  - "make"
  - "ln -s $(pwd)/libtidy.so.5.5.31 $LD_LIBRARY_PATH/libtidy-0.99.so.0"
  - "popd"
  - "gem install sass"
  - "npm install uglify-js"
  - "export PATH=$(pwd)/node_modules/.bin:\"$PATH\""
  - "popd"
  - "mkdir -p aux"
  - "wget https://www.pecina.cz/files/vnu.jar -O aux/vnu.jar"
  - |
    if [ "$DJANGO_VERSION" == nightly ]; then
        pip install git+https://github.com/django/django.git
        pip install -r <(cat requirements.txt | grep -v -e '^Django==')
    else
        pip install -r requirements.txt
    fi

install:
  - "./make-static"

script:
  - "./full-test"

after_success:
  - "if [ -n \"$DEPLOY\" ]; then ./deploy; fi"
