# .travis.yml

language: "python"

sudo:  "false"

python:
  - "3.5"
  - "3.6"
  - "nightly"

addons:
  apt:
    packages:
    - "ruby-dev"

env:
  global:
    - "TEST=1"
    - "DBUSER=root"
  matrix:
    - "DJANGO_VERSION=stable"
    - "DJANGO_VERSION=nightly"

before_install:
  - "git clone --depth=1 https://github.com/htacg/tidy-html5.git"
  - "cd tidy-html5/build/cmake/"
  - "cmake ../.. -DCMAKE_BUILD_TYPE=Bin"
  - "make"
  - "cd -"
  - "ln -s /home/travis/tompecina/legal/tidy-html5/build/cmake/libtidy.so.5.5.31 ./libtidy-0.99.so.0"
  - "gem install sass"
  - |
    if [ "$DJANGO_VERSION" == nightly ]; then
        pip install git+https://github.com/django/django.git
        pip install -r <(cat requirements.txt | grep -v -e '^Django==')
    else
        pip install -r requirements.txt
    fi

install:
  - "./dosass"
  - "./manage.py collectstatic --noinput --ignore='*.scss' --ignore='*.map'" 

script:
  - "LD_PRELOAD=./libtidy-0.99.so.0 ./manage.py test tests --failfast && ./manage.py test tests --reverse --failfast"
