# .travis.yml
services:
  - mysql
language: python
python:
  - "3.5"
env:
  - DBUSER=root
before_install:
  - "mysql -e 'CREATE DATABASE IF NOT EXISTS test_legal;'"
install: "pip install -r requirements.txt"
script: "./manage.py test"
