# .travis.yml

language: "python"

sudo:  "false"

python:
  - "3.5"
  - "3.6"

env:
  global:
    - "TEST=1"
    - "DBUSER=root"
  matrix:
    - "DJANGO_VERSION=stable CHECK_HTML=1"
    - "DJANGO_VERSION=nightly"

before_install:
  - "pushd ~/builds"
  - "mkdir -p lib"
  - "export LD_LIBRARY_PATH=$(pwd)/lib"
  - "git clone --depth=1 https://github.com/htacg/tidy-html5.git htacg/tidy-html5"
  - "pushd htacg/tidy-html5/build/cmake"
  - "cmake ../.. -DCMAKE_BUILD_TYPE=Release"
  - "make"
  - "ln -s $(pwd)/libtidy.so.5.5.31 $LD_LIBRARY_PATH/libtidy-0.99.so.0"
  - "popd"
  - "gem install sass"
  - "npm install uglify-js"
  - "export PATH=$(pwd)/node_modules/.bin:\"$PATH\""
  - "npm install vnu-jar"
  - "ln -s $(pwd)/node_modules/vnu-jar/build/dist/vnu.jar $LD_LIBRARY_PATH"
  - "popd"
  - |
    if [ "$DJANGO_VERSION" == nightly ]; then
        pip install git+https://github.com/django/django.git
        pip install -r <(cat requirements.txt | grep -v -e '^Django==')
    else
        pip install -r requirements.txt
    fi

install:
  - "./make-static"

script:
  - >
    DUMP_PATH=tests/temp ./manage.py test tests --failfast
    && ./manage.py test tests --reverse --failfast
    && java -jar $LD_LIBRARY_PATH/vnu.jar --no-langdetect tests/temp/*.html
